/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 hack.gltf --transform
Author: Pavel Zhovner (https://sketchfab.com/zhovner)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/flipper-zero-1f246cff5f03472283f4e52fb0c84684
Title: Flipper Zero
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/hack-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.New_material_007} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.New_material_011} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.Default} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.New_material_003} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.New_material_003} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.New_material_010} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.New_material_008} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.New_material_008} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.New_material_008} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.New_material_009} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.New_material_012} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.New_material_012} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.New_material_013} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.New_material_014} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.New_material_015} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.New_material_015} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.New_material_015} />
      </group>
    </group>
  )
}

useGLTF.preload('/hack-transformed.glb')
